title: FASCO 外航服务公司 / Foreign Airlines Service
email: info@gzfasco.com
url: https://gzfasco.github.io
baseurl: "can-fasco"
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
